baseURL = "http://localhost:1313/"
languageCode = "en-gb"
title = "DocString.me"
theme = "PaperMod"

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true

[params.homeInfoParams]
Title = "Welcome"
Content = "Articles about technical writing, AI, documentation, and technology."

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 20
